### ISSUE TITLE
A little trouble.

### ISSUE THREAD

**Issue by findborg** [inca/voie-starter-webpack#1] opened 2015-12-31 23:23 UTC
This is just what I was looking for from you.  A simple example.  However,  I am having trouble  getting it to run.
`ERROR in ./src/main.js
Module parse failed: /opt/lampp/htdocs/states/node_modules/babel-loader/index.js!/opt/lampp/htdocs/states/src/main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import app from './app';
| import './states';
| 
`

**Comment by findborg** [comment] 2016-01-01 08:40
Ok Inca,  It does work just fine if I follow your install directions.  I really like it.  Now I will play around with it to see what I can learn.   I really want to get set up outside of the dev server on my dev machine.  That will be the first thing I try.  But,  looking good.

**Comment by findborg** [comment] 2016-01-01 16:40
Good News!  I got it working using the "webpack"  command.   I had to change the state routes because I was testing in a sub folder.  But,  it is now working for me.
`
app.add('layout', {
  redirect: 'home',
  component: Layout
});

app.add('home', {
  path: '/states',
  parent: 'layout',
  component: Home
});

app.add('a', {
  path: '/states/a',
  parent: 'layout',
  component: A
});

app.add('b', {
  path: '/states/b',
  parent: 'layout',
  component: B
});
`

**Comment by inca** [comment] 2016-01-01 17:58
Great! Have fun ;)

**Comment by findborg** [comment] 2016-01-04 06:20
Just a quick update.  I am loving this.  As you have probably figured out.  I am learning all of this as I go.  But,  I have figured out how to add separate sections into the routes. Plus the basics you setup with this example.  I will upload to live site soon so that you can see what I am working on if you are interested.  Anyway,  thanks for all your help.

**Comment by Teknologica** [comment] 2016-02-11 22:13
I actually have the same error @findborg encountered originally:

```
ERROR in ./~/voie/src/index.js
Module parse failed: C:\github\abc\node_modules\voie\src\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import StateManager from './state-manager';
| import State from './state';
| import Transition from './transition';
 @ ./src/routing.js 7:12-27
```

How did you fix this? Babel seems to be configured correctly, so does Webpack.

**Comment by inca** [comment] 2016-02-12 09:15
This error is about ES6 modules (`import` and `export` keywords). To support those you need `babel-preset-es2015` and `babel-plugin-transform-runtime` dev dependencies along with following babel configuration (`.babelrc`):

```
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"]
}
```

**Comment by Teknologica** [comment] 2016-02-12 14:31
That's the thing though, those are installed. 
From `package.json`:

``` js
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
```

From `.babelrc`:

``` js
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

From webpack config:

``` js
//module.loaders: []
{
    test: /\.js$/,
    loader: 'babel',
},
```

I use `import` and `export` elsewhere without any issues. The line it points at in the error looks like this: 

``` js
let routing = new StateManager({
    el: '#abc'
});

export default routing;
```

I will keep looking for a solution. `voie` is the best option for my project's routing/layout managing right now. Great job by the way.

**Comment by inca** [comment] 2016-02-12 20:11
Hm, I just ran voie-starter-webpack with updated dependencies without any issues. I'm no webpack-expert (neither a user), so I'd start with checking your configuration against [ours](https://github.com/inca/voie-starter-webpack/blob/master/webpack.config.js) (for example, I don't know, but you might need to exclude `node_modules` from `babel` loader explicitly like we did).

**Comment by Teknologica** [comment] 2016-02-12 20:17
I've been trying a few things. It seems to be a more common problem than expected but not limited to `voie` (also found for React). [Here's my current conf](https://gist.github.com/Teknologica/c6c2b36261f7f3211580).

**Comment by Teknologica** [comment] 2016-02-12 21:48
Small update: I can reproduce this problem whenever I use the `vue-cli webpack` template.

I create a new project via `vue-cli`:

```
$ vue init webpack voie-test
$ cd voie-test
$ npm i css-loader style-loader voie --save
$ npm install
```

Then I modify the `webpack` config to remove the automatic `eslint` loader setting that the `vue-cli` template adds. Finally I copy the structure inside the `/src` folder of  `voie-starter-webpack` and run `npm run dev`.

Same error occurs: 

```
ERROR in ./~/voie/src/index.js
Module parse failed: C:\GitHub\voie-test\node_modules\voie\src\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import StateManager from './state-manager';
| import State from './state';
| import Transition from './transition';
 @ ./src/app.js 7:12-27
```

My guess is something inside the `webpack` template of `vue-cli`, probably some setting, is the cause of this issue right now. I still haven't found what exactly.

**Comment by Teknologica** [comment] 2016-02-15 15:59
Update. I installed the latest version of Node then I forked the `vue-cli` webpack template and removed ES Lint from the file, added `voie` to the package.json and used the new template to instantiate my project. Now it builds fine without errors. Hopefully this fixed it forever!

**Comment by inca** [comment] 2016-02-15 16:40
Glad it finally worked out for you! I don't think eslint is the cause (I use it all the time), so it should have something to do with node version — or just good luck :D

Closing; feel free to reopen if you have some more issues or updates.

**Closed as completed by inca** 2016-02-15 16:40 UTC
